
export const columns=[
    {
        title:'序号',
        dataIndex:'key'
    },
    {
        title:'账户编号',
        dataIndex:'field1'
    },
    {
        title:'账户名称',
        dataIndex:'field2'
    },
    {
        title:'当前余额',
        dataIndex:'field3'
    },
    {
        title:'期初余额',
        dataIndex:'field4'
    },
    {
        title:'建账日期',
        dataIndex:'field5'
    },
    {
        title:'账户类别',
        dataIndex:'field6'
    }
]