export const columns=[
    {
        title:'序号',
        dataIndex:'key'
    },
    {
        title:'客户类别',
        dataIndex:'field1'
    },
    {
        title:'客户等级',
        dataIndex:'field2'
    },
    {
        title:'客户编号',
        dataIndex:'field3'
    },
    {
        title:'客户名称',
        dataIndex:'field4'
    },
    {
        title:'联系人',
        dataIndex:'field5'
    },
    {
        title:'手机',
        dataIndex:'field6'
    },
    {
        title:'应收款余额',
        dataIndex:'field7'
    },
    {
        title:'地址',
        dataIndex:'field8'
    }    
]