import uuid from 'uuid/v4'
export default [
    {
        id:uuid(),
        type:'col',
        title:'布局容器',
        icon:'layout'
    },
    {
        id:uuid(),
        type:'text',
        title:'纯文本',
        icon:'font-size'
    },
    {
        id:uuid(),
        type:'input',
        title:'单行输入框',
        icon:'edit'
    },
    {
        id:uuid(),
        type:'textarea',
        title:'多行输入框',
        icon:'form'
    },
    {
        id:uuid(),
        type:'date',
        title:'日期',
        icon:'calendar'
    },
    {
        id:uuid(),
        type:'select',
        title:'下拉框',
        icon:'select'
    },
    {
        id:uuid(),
        type:'radio',
        title:'单选框',
        icon:'tag'
    },
    {
        id:uuid(),
        type:'checkbox',
        title:'复选框',
        icon:'tags'
    },
    {
        id:uuid(),
        type:'table',
        title:'自定义表格',
        icon:'table'
    },
    
]